services:
  backend:
    image: wings-backend-img
    build: 
      context: ./aspnetapp
      dockerfile: Dockerfile
    container_name: wings-backend-ctr
    volumes:
      - "./aspnetapp/WINGS/TlmCmd:/app/TlmCmd" 
      - "./aspnetapp/WINGS/Logs:/app/Logs"
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql; uid=root; pwd=P@ssw0rd!; database=wings;"
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      HTTP_PORTS: "5000"
      HTTPS_PORTS: ""
      ASPNETCORE_HTTPS_PORT: ""
    ports:
      - "5000:5000"  
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wings-network

  frontend:
    image: wings-frontend-dev-img
    build:
      context: ./ClientApp
    container_name: wings-frontend-ctr
    volumes:
      - "./ClientApp:/app"
      - "/app/node_modules"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wings-network

  mysql:
    image: wings-mysql-img
    build: ./mysql
    container_name: wings-mysql-ctr
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=wings
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pP@ssw0rd!"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s
    networks:
      - wings-network

networks:
  wings-network:
    driver: bridge
