version: "3"
services:
  aspnetapp:
    image: wings-aspnetapp-img
    build: ./aspnetapp
    container_name: wings-aspnetapp-ctr
    volumes:
      - "./aspnetapp/WINGS/TlmCmd:/app/TlmCmd" 
      - "./aspnetapp/WINGS/Logs:/app/Logs"
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql; uid=root; pwd=P@ssw0rd!; database=wings;"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: "P@ssw0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/certificate.pfx"
    ports:
      - "5001:5001"
    depends_on:
      - mysql
  mysql:
    image: wings-mysql-img
    build: ./mysql
    container_name: wings-mysql-ctr
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=wings
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
