// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WINGS.Data;

#nullable disable

namespace WINGS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WINGS.Models.CommandLog", b =>
                {
                    b.Property<string>("OperationId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(1)");

                    b.Property<string>("CmdName")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("ExecTime")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ExecType")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param1")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param2")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param3")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param4")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param5")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Param6")
                        .HasColumnType("varchar(64)");

                    b.HasKey("OperationId", "SentAt");

                    b.ToTable("CommandLogs");
                });

            modelBuilder.Entity("WINGS.Models.Component", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LocalDirPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TcPacketKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TmPacketKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("WINGS.Models.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(0)");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTmtcConnected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PathNumber")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TmtcTarget")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("WINGS.Models.CommandLog", b =>
                {
                    b.HasOne("WINGS.Models.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("WINGS.Models.Operation", b =>
                {
                    b.HasOne("WINGS.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");
                });
#pragma warning restore 612, 618
        }
    }
}
